name: magveto_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  infinite_carousel: ^1.0.2
  provider: ^6.0.5

flutter:
  uses-material-design: true
